# Generated by Django 5.1.3 on 2025-05-18 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_remove_movie_genres_delete_genre_movie_genres'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='movie',
            unique_together=set(),
        ),
    ]
